version: "3.8"

services:
  producer:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE: producer
    ports:
      - "8080:8080"
    volumes:
      - ./producer:/app
    environment:
      ENVIRONMENT: development
      SERVICE_NAME: producer

  consumer:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE: consumer
    ports:
      - "8901:8901"
    volumes:
      - ./consumer:/app
    environment:
      ENVIRONMENT: development
      SERVICE_NAME: consumer