server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
    relabel_configs:
      - source_labels: [__meta_docker_container_name]
        target_label: app
        regex: '(?:.*[/])?([^/]+)$'
        replacement: '$1'
      - source_labels: [__meta_docker_container_id]
        target_label: container_id
      - source_labels: [__meta_docker_container_image]
        target_label: container_image
      - source_labels: [__meta_docker_container_label_com_docker_compose_service]
        target_label: compose_service
      - source_labels: [__meta_docker_container_label_com_docker_compose_project]
        target_label: compose_project
      - source_labels: [__meta_docker_container_label_com_docker_compose_oneoff]
        target_label: compose_oneoff
      - source_labels: [__meta_docker_container_label_com_docker_compose_config_hash]
        target_label: compose_config_hash
      - source_labels: [__meta_docker_container_label_com_docker_compose_version]
        target_label: compose_version

    pipeline_stages:
      - json:
          expressions:
            trace_id: trace_id
            span_id: span_id
            log_level: level
            message: msg
            time: time
            caller: caller
      - timestamp:
          source: time
          format: RFC3339Nano
      - labels:
          trace_id: trace_id
          span_id: span_id
          level: log_level
          caller: caller
