global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'consumer'
    static_configs:
      - targets: ['host.docker.internal:8901']
  - job_name: 'producer'
    static_configs:
      - targets: ['host.docker.internal:8080']
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres_exporter:9187']
    scrape_interval: 10s
    metrics_path: /metrics
  - job_name: 'nats'
    static_configs:
      - targets: ['nats_exporter:7777']
    scrape_interval: 15s
    metrics_path: /metrics
    scrape_timeout: 10s
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
